CREATE TABLE ADMNISTRATIVOS 
(
  IDADMINISTRATIVO NUMBER(9, 0) NOT NULL 
, RUNAD NUMBER(9, 0) 
, NOMBRESAD VARCHAR2(40 BYTE) NOT NULL 
, APELLIDOSAD VARCHAR2(40 BYTE) NOT NULL 
, CORREOE VARCHAR2(50 BYTE) NOT NULL 
, AREA VARCHAR2(30 BYTE) NOT NULL 
);




CREATE TABLE CAPACITACION 
(
  IDCAPACITACION NUMBER(9, 0) 
, CAPFECHA DATE NOT NULL 
, CAPHORA DATE 
, CAPLUGAR VARCHAR2(100 BYTE) NOT NULL 
, CAPDURACION NUMBER(4, 0) 
, CLIENTE_RUTCLIENTE NUMBER(9, 0) 
, CAPCANTIDAD NUMBER(*, 0) 
);


CREATE TABLE CLIENTE 
(
  IDCLIENTE NUMBER(9, 0) NOT NULL 
, RUTCLIENTE NUMBER(9, 0) 
, CLINOMBRES VARCHAR2(30 BYTE) NOT NULL 
, CLIAPELLIDOS VARCHAR2(50 BYTE) NOT NULL 
, CLITELEFONO VARCHAR2(20 BYTE) NOT NULL 
, CLIAFP VARCHAR2(30 BYTE) 
, CLISISTEMASALUD NUMBER(2, 0) 
, CLIDIRECCION VARCHAR2(100 BYTE) NOT NULL 
, CLICOMUNA VARCHAR2(50 BYTE) NOT NULL 
, CLIEDAD NUMBER(3, 0) NOT NULL 
) ;




CREATE TABLE PROFESIONALES 
(
  IDPROFESIONAL NUMBER(9, 0) NOT NULL 
, RUNPRO NUMBER(9, 0) 
, NOMBRESPRO VARCHAR2(40 BYTE) NOT NULL 
, APELLIDOSPRO VARCHAR2(40 BYTE) NOT NULL 
, TELEFONO VARCHAR2(20 BYTE) NOT NULL 
, TITULOPRO VARCHAR2(30 BYTE) NOT NULL 
, PROYECTO VARCHAR2(240 BYTE) NOT NULL 
);







